// Generates everything in this package that is not written by hand:
//
//   catalog.json              the permission catalog, read out of the SQL
//   openapi.json              the API as OpenAPI 3.1
//   src/generated/catalog.ts  the catalog, typed
//   src/generated/types.ts    every shape the API sends or receives
//   src/generated/routes.ts   the route table and its request/response types
//   src/generated/errors.ts   error codes and their HTTP status
//
// Sources: spec/*.mjs for the API, ../db/migrations for the catalog. Run with
// `npm run generate` after changing either; CI checks nothing is left stale.

import { PGlite } from '@electric-sql/pglite';
import { btree_gist } from '@electric-sql/pglite/contrib/btree_gist';
import { citext } from '@electric-sql/pglite/contrib/citext';
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { endpoints, pathParamTypes } from '../spec/endpoints.mjs';
import { errors } from '../spec/errors.mjs';
import { enums, objects } from '../spec/models.mjs';

const here = join(dirname(fileURLToPath(import.meta.url)), '..');
const dbDir = join(here, '..', 'db');
const pkg = JSON.parse(readFileSync(join(here, 'package.json'), 'utf8'));
const banner = '// Generated by scripts/generate.mjs — do not edit.\n';

// --- 1. The catalog, straight from the SQL -----------------------------------

const db = new PGlite({ extensions: { btree_gist, citext } });
for (const f of readdirSync(join(dbDir, 'migrations')).filter((f) => f.endsWith('.sql')).sort()) {
  await db.exec(readFileSync(join(dbDir, 'migrations', f), 'utf8'));
}
const rows = async (sql) => (await db.query(sql)).rows;
const catalog = {
  modules: await rows(`select key, name, sort_order as "sortOrder" from modules order by sort_order`),
  roleDefaults: await rows(`select role, module, level, max_level as "maxLevel"
                            from role_module_defaults order by role, module`),
  roleCanCreate: await rows(`select creator_role as "creatorRole", created_role as "createdRole"
                             from role_can_create order by 1, 2`),
  actions: await rows(`select key, module, min_level as "minLevel", destructive,
                              owner_only as "ownerOnly", description
                       from actions order by key`),
};
await db.close();
const actionByKey = Object.fromEntries(catalog.actions.map((a) => [a.key, a]));

// Every action an endpoint names must exist in the SQL.
for (const ep of endpoints) {
  if (ep.action && !actionByKey[ep.action]) {
    throw new Error(`${ep.method} ${ep.path} names unknown action ${ep.action}`);
  }
}

const allEnums = {
  ...enums,
  ModuleKey: { kind: 'enum', values: catalog.modules.map((m) => m.key), doc: 'From the SQL catalog.' },
  ActionKey: { kind: 'enum', values: catalog.actions.map((a) => a.key), doc: 'From the SQL catalog.' },
  ErrorCode: { kind: 'enum', values: errors.map(([code]) => code) },
};

// --- 2. OpenAPI 3.1 -----------------------------------------------------------

const refPath = (name) => `#/components/schemas/${name}`;

function oas(s) {
  let o;
  switch (s.kind) {
    case 'integer':
      o = { type: 'integer' };
      if (s.format) o.format = s.format;
      if (s.minimum !== undefined) o.minimum = s.minimum;
      if (s.maximum !== undefined) o.maximum = s.maximum;
      break;
    case 'number':
      o = { type: 'number' };
      if (s.multipleOf) o.multipleOf = s.multipleOf;
      break;
    case 'string':
      o = { type: 'string' };
      if (s.format) o.format = s.format;
      if (s.pattern) o.pattern = s.pattern;
      break;
    case 'boolean': o = { type: 'boolean' }; break;
    case 'any': o = {}; break;
    case 'ref': o = { $ref: refPath(s.name) }; break;
    case 'array': o = { type: 'array', items: oas(s.items) }; break;
    case 'map':
      o = { type: 'object', additionalProperties: oas(s.values) };
      if (s.keyEnum) o.propertyNames = { $ref: refPath(s.keyEnum) };
      break;
    default: throw new Error(`unknown kind ${s.kind}`);
  }
  if (s.nullable && s.kind !== 'any') {
    o = o.$ref || o.type === undefined ? { anyOf: [o, { type: 'null' }] } : { ...o, type: [o.type, 'null'] };
  }
  if (s.doc) o.description = s.doc;
  return o;
}

function oasNamed(s) {
  if (s.kind === 'enum') return { type: 'string', enum: s.values, ...(s.doc && { description: s.doc }) };
  const properties = {};
  const required = [];
  for (const [k, v] of Object.entries(s.properties)) {
    properties[k] = oas(v);
    if (!v.optional) required.push(k);
  }
  return {
    type: 'object',
    ...(s.doc && { description: s.doc }),
    properties,
    ...(required.length && { required }),
  };
}

const schemas = {};
for (const [name, s] of Object.entries({ ...allEnums, ...objects })) schemas[name] = oasNamed(s);

const pathParams = (path) => [...path.matchAll(/:(\w+)/g)].map((m) => m[1]);
const oasPath = (path) => path.replace(/:(\w+)/g, '{$1}');
const opId = (ep) => {
  const words = ep.path.replace(/^\/v1\//, '').split(/[/-]/).filter(Boolean)
    .map((w) => (w.startsWith(':') ? `By${w[1].toUpperCase()}${w.slice(2)}` : w));
  return ep.method.toLowerCase() + words.map((w) => w[0].toUpperCase() + w.slice(1)).join('');
};
const tagOf = (ep) => {
  const [, , first, second] = ep.path.split('/');
  return first === 'platform' ? `platform/${second}` : first;
};

const paths = {};
const seenIds = new Set();
for (const ep of endpoints) {
  const operationId = opId(ep);
  if (seenIds.has(operationId)) throw new Error(`duplicate operationId ${operationId}`);
  seenIds.add(operationId);
  const action = ep.action ? actionByKey[ep.action] : null;

  const parameters = [
    ...pathParams(ep.path).map((name) => ({
      name, in: 'path', required: true,
      schema: oas(pathParamTypes[name] ?? { kind: 'integer', format: 'int64' }),
    })),
    ...Object.entries(ep.query ?? {}).map(([name, s]) => ({
      name, in: 'query', required: !s.optional,
      ...(s.kind === 'array' && { style: 'form', explode: false }),
      schema: oas({ ...s, optional: undefined }),
    })),
  ];

  const op = {
    operationId,
    summary: ep.summary,
    tags: [tagOf(ep)],
    ...(parameters.length && { parameters }),
  };

  if (ep.body === 'multipart') {
    op.requestBody = {
      required: true,
      content: {
        'multipart/form-data': {
          schema: {
            type: 'object',
            required: ['purpose', 'file'],
            properties: {
              purpose: { $ref: refPath('FilePurpose') },
              file: { type: 'string', contentMediaType: 'application/octet-stream' },
            },
          },
        },
      },
    };
  } else if (ep.body) {
    op.requestBody = { required: true, content: { 'application/json': { schema: oas(ep.body) } } };
  }

  const errorResponse = { description: 'An error.', content: { 'application/json': { schema: { $ref: refPath('ApiError') } } } };
  if (ep.response === null) op.responses = { 204: { description: 'Done.' } };
  else if (ep.response === 'redirect') op.responses = { 302: { description: 'To a signed URL.' } };
  else if (ep.response === 'sse') op.responses = { 200: { description: 'An event stream.', content: { 'text/event-stream': {} } } };
  else op.responses = { 200: { description: 'OK.', content: { 'application/json': { schema: oas(ep.response) } } } };
  op.responses.default = errorResponse;

  op.security = ep.auth === 'none' ? [] : [{ bearer: [] }];
  if (action) {
    op['x-action'] = action.key;
    op['x-destructive'] = action.destructive;
    op['x-owner-only'] = action.ownerOnly;
  }
  if (ep.platform) op['x-platform-role'] = ep.platform;

  (paths[oasPath(ep.path)] ??= {})[ep.method.toLowerCase()] = op;
}

const openapi = {
  openapi: '3.1.0',
  info: {
    title: 'StitchFlow API',
    version: pkg.version,
    description:
      'The contract between the StitchFlow apps, the web admin panel and the API. ' +
      'Every operation names the permission action it needs (x-action); a destructive ' +
      'action is super admin only. Dates without a time are "YYYY-MM-DD"; instants are ' +
      'ISO-8601 UTC; money is rounded to the paisa. See HANDOVER.md.',
  },
  servers: [{ url: 'https://api.example.com', description: 'Replace per environment.' }],
  components: {
    securitySchemes: { bearer: { type: 'http', scheme: 'bearer', bearerFormat: 'JWT' } },
    schemas,
  },
  paths,
};

// --- 3. TypeScript ------------------------------------------------------------

const wrap = (t) => (t.includes('|') ? `(${t})` : t);
function ts(s) {
  let t;
  switch (s.kind) {
    case 'integer':
    case 'number': t = 'number'; break;
    case 'string': t = s.ts ?? 'string'; break;
    case 'boolean': t = 'boolean'; break;
    case 'any': t = 'unknown'; break;
    case 'ref': t = s.name; break;
    case 'array': t = `${wrap(ts(s.items))}[]`; break;
    case 'map': t = s.keyEnum ? `Partial<Record<${s.keyEnum}, ${ts(s.values)}>>` : `Record<string, ${ts(s.values)}>`; break;
    default: throw new Error(`unknown kind ${s.kind}`);
  }
  return s.nullable && t !== 'unknown' ? `${t} | null` : t;
}
const jsdoc = (text, indent = '') => (text ? `${indent}/** ${text.replace(/\*\//g, '* /')} */\n` : '');
const lit = (v) => JSON.stringify(v);

let types = `${banner}
import type { ActionKey, ModuleKey } from './catalog.js';
import type { ErrorCode } from './errors.js';

export type { ActionKey, ModuleKey, ErrorCode };

/** A calendar date with no time: "YYYY-MM-DD". */
export type DateOnly = string;
/** An instant, ISO-8601 UTC: "2026-09-27T09:30:00Z". */
export type Instant = string;
/** A calendar month: "YYYY-MM". */
export type Month = string;
`;
for (const [name, s] of Object.entries(enums)) {
  types += `\n${jsdoc(s.doc)}export type ${name} = ${s.values.map(lit).join(' | ')};\n`;
  types += `export const ${name}Values = [${s.values.map(lit).join(', ')}] as const;\n`;
}
for (const [name, s] of Object.entries(objects)) {
  types += `\n${jsdoc(s.doc)}export interface ${name} {\n`;
  for (const [k, v] of Object.entries(s.properties)) {
    types += `${jsdoc(v.doc, '  ')}  ${k}${v.optional ? '?' : ''}: ${ts(v)};\n`;
  }
  types += '}\n';
}

let routes = `${banner}
import type * as T from './types.js';
import type { ActionKey } from './catalog.js';

export type HttpMethod = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';

/**
 * Every route, keyed "METHOD /path". params are the path's :names, query the
 * query string, body the JSON body (FormData for an upload), response what a
 * 2xx carries (void for 204, a redirect or a stream).
 */
export interface ApiRoutes {
`;
const routeRows = [];
for (const ep of endpoints) {
  const key = `${ep.method} ${ep.path}`;
  const params = pathParams(ep.path).map((p) => `${p}: ${pathParamTypes[p] ? (pathParamTypes[p].kind === 'ref' ? `T.${pathParamTypes[p].name}` : 'string') : 'number'}`);
  const query = Object.entries(ep.query ?? {}).map(([k, v]) => `${k}${v.optional ? '?' : ''}: ${qualify(ts({ ...v, optional: undefined }))}`);
  const body = ep.body === 'multipart' ? 'FormData' : ep.body ? qualify(ts(ep.body)) : 'undefined';
  const response = typeof ep.response === 'object' && ep.response !== null ? qualify(ts(ep.response)) : 'void';
  routes += `${jsdoc(ep.summary, '  ')}  ${lit(key)}: {\n` +
    `    params: { ${params.join('; ')} };\n` +
    `    query: { ${query.join('; ')} };\n` +
    `    body: ${body};\n` +
    `    response: ${response};\n  };\n`;
  const action = ep.action ? actionByKey[ep.action] : null;
  routeRows.push({
    key, method: ep.method, path: ep.path, summary: ep.summary,
    action: ep.action ?? null,
    auth: ep.auth ?? (ep.platform ? 'platform' : 'member'),
    platformRole: ep.platform ?? null,
    destructive: action?.destructive ?? false,
    ownerOnly: action?.ownerOnly ?? false,
  });
}
routes += `}

export type RouteKey = keyof ApiRoutes;

export interface RouteInfo {
  key: RouteKey;
  method: HttpMethod;
  /** Express/Fastify style, with :params. */
  path: string;
  summary: string;
  /** The permission the route needs, or null for sign-in and session routes. */
  action: ActionKey | null;
  /** none: no token. session: any signed-in user. member: the action below. platform: console staff. */
  auth: 'none' | 'session' | 'member' | 'platform';
  platformRole: T.PlatformRole | null;
  destructive: boolean;
  ownerOnly: boolean;
}

export const ROUTES: readonly RouteInfo[] = ${JSON.stringify(routeRows, null, 2)};
`;

function qualify(t) {
  // Prefix named types with T. inside routes.ts; leave primitives alone.
  const prims = new Set(['number', 'string', 'boolean', 'unknown', 'null', 'undefined', 'void', 'Partial', 'Record']);
  return t.replace(/\b([A-Z][A-Za-z]+)\b/g, (m) => (prims.has(m) ? m : `T.${m}`));
}

let catalogTs = `${banner}
import type { AccessLevel, UserRole } from './types.js';

export const MODULES = ${JSON.stringify(catalog.modules, null, 2)} as const;
export type ModuleKey = (typeof MODULES)[number]['key'];

export interface ActionInfo {
  module: ModuleKey;
  minLevel: 'view' | 'edit';
  /** Super admin only, whatever the module level. */
  destructive: boolean;
  /** The property's main super admin only. */
  ownerOnly: boolean;
  description: string;
}

export const ACTIONS = {
${catalog.actions.map((a) => `  ${lit(a.key)}: { module: ${lit(a.module)}, minLevel: ${lit(a.minLevel)}, destructive: ${a.destructive}, ownerOnly: ${a.ownerOnly}, description: ${lit(a.description)} },`).join('\n')}
} as const satisfies Record<string, ActionInfo>;
export type ActionKey = keyof typeof ACTIONS;

/** Each role's default level and ceiling per module. */
export const ROLE_DEFAULTS: Record<UserRole, Record<ModuleKey, { level: AccessLevel; maxLevel: AccessLevel }>> = {
${[...new Set(catalog.roleDefaults.map((d) => d.role))].map((role) =>
  `  ${role}: {\n${catalog.roleDefaults.filter((d) => d.role === role)
    .map((d) => `    ${d.module}: { level: ${lit(d.level)}, maxLevel: ${lit(d.maxLevel)} },`).join('\n')}\n  },`).join('\n')}
};

/** Which roles each role may create. Only the owner creates super admins. */
export const ROLE_CAN_CREATE: Record<UserRole, readonly Exclude<UserRole, 'superAdmin'>[]> = {
${['superAdmin', 'admin', 'viewAdmin', 'supervisor', 'worker'].map((role) =>
  `  ${role}: [${catalog.roleCanCreate.filter((c) => c.creatorRole === role).map((c) => lit(c.createdRole)).join(', ')}],`).join('\n')}
};
`;

const errorsTs = `${banner}
export type ErrorCode = ${errors.map(([c]) => lit(c)).join(' | ')};

/** The HTTP status each code is sent with. */
export const ERROR_STATUS: Record<ErrorCode, number> = {
${errors.map(([c, s]) => `  ${c}: ${s},`).join('\n')}
};

/** What each code means, and what its details carry. */
export const ERROR_MEANING: Record<ErrorCode, string> = {
${errors.map(([c, , m]) => `  ${c}: ${lit(m)},`).join('\n')}
};
`;

// --- 4. Write -----------------------------------------------------------------

const out = (rel, text) => {
  const file = join(here, rel);
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, text);
};
out('catalog.json', `${JSON.stringify(catalog, null, 2)}\n`);
out('openapi.json', `${JSON.stringify(openapi, null, 2)}\n`);
out('src/generated/types.ts', types);
out('src/generated/routes.ts', routes);
out('src/generated/catalog.ts', catalogTs);
out('src/generated/errors.ts', errorsTs);

console.log(`generated: ${Object.keys(schemas).length} schemas, ${endpoints.length} endpoints, ` +
  `${catalog.actions.length} actions, ${catalog.modules.length} modules, ${errors.length} error codes`);
